# Generated by Django 5.0.6 on 2024-08-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ShipmentAddress',
        ),
    ]
