# Generated by Django 5.0.6 on 2024-08-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_remove_payment_shipmentaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Order',
            new_name='order',
        ),
    ]
