# Generated by Django 5.0.6 on 2024-08-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order',
            new_name='orders',
        ),
    ]
