# Generated by Django 5.0.2 on 2024-08-01 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0023_remove_order_shipping_address'),
        ('checkout', '0003_shoppineaddress_delete_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppineaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='shoppineaddress',
            name='orders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Order.order'),
            preserve_default=False,
        ),
    ]
