# Generated by Django 5.0.6 on 2024-07-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_alter_orderdetails_order_alter_orderdetails_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
