# Generated by Django 5.0.6 on 2024-07-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_alter_orderdetails_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
