# Generated by Django 5.0.6 on 2024-07-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_rename_total_orderdetails_total_amuont'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
