# Generated by Django 5.0.6 on 2024-07-26 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0012_orderdetails_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='total_amuont',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='unit_price',
        ),
    ]
