# Generated by Django 5.0.2 on 2024-07-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_remove_orderdetails_total_amuont_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
