# Generated by Django 5.0.2 on 2024-07-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0015_rename_unit_price_orderdetails_price_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='price_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
