# Generated by Django 5.0.2 on 2024-07-28 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0016_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='price_unit',
            new_name='unit_price',
        ),
    ]
