# Generated by Django 5.0.2 on 2024-07-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0017_rename_price_unit_orderdetails_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
