# Generated by Django 5.0.2 on 2024-07-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0019_coupon_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
