# Generated by Django 5.0.2 on 2024-07-28 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0020_remove_order_coupon_delete_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='unit_price',
        ),
    ]
