# Generated by Django 5.0.2 on 2024-07-30 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0021_remove_orderdetails_unit_price'),
        ('checkout', '0002_remove_checkout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='checkout.checkout'),
        ),
    ]
