# Generated by Django 5.0.2 on 2024-08-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0022_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
