# Generated by Django 5.0.6 on 2024-06-27 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('Price', models.PositiveIntegerField()),
                ('DiscountPrice', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('Stock', models.PositiveIntegerField()),
                ('photo', models.ImageField(upload_to='Product/')),
                ('color', models.CharField(choices=[('Read', 'Read'), ('Green', 'Green'), ('Black', 'Black'), ('White', 'White'), ('Blue', 'Blue')], max_length=255)),
                ('size', models.CharField(choices=[('s', 'S'), ('xs', 'Xs'), ('m', 'M'), ('l', 'L'), ('xl', 'Xl'), ('xxl', 'Xxl')], max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.categorys')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
