# Generated by Django 5.0.6 on 2024-06-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_reviwe_create_reviwe_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviwe',
        ),
    ]
