# Generated by Django 5.0.6 on 2024-06-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_delete_reviwe'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ratings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
