# Generated by Django 5.0.6 on 2024-07-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
