# Generated by Django 5.0.6 on 2024-07-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='DiscountPrice',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
