# Generated by Django 5.0.6 on 2024-07-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_products_discountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='DiscountPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='products',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
