# Generated by Django 5.0.2 on 2024-07-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_products_discountprice_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='DiscountPrice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='Price',
            field=models.PositiveIntegerField(),
        ),
    ]
